import { defineConfig } from "oxlint"

export default defineConfig({
  plugins: ["eslint", "typescript", "unicorn", "oxc", "import", "node", "promise"],
  jsPlugins: ["@stylistic/eslint-plugin"],
  options: {
    typeAware: true,
    typeCheck: true,
    maxWarnings: 0,
  },
  env: {
    builtin: true,
    node: true,
  },
  rules: {
    "@stylistic/line-comment-position": ["error", { position: "above" }],
    "@stylistic/linebreak-style": ["error", "unix"],
    "@stylistic/multiline-comment-style": ["error", "separate-lines"],
    "@stylistic/padded-blocks": ["error", "never"],
    "@stylistic/padding-line-between-statements": [
      "error",
      {
        blankLine: "always",
        next: [
          "break",
          "case",
          "cjs-export",
          "class",
          "continue",
          "do",
          "export",
          "if",
          "switch",
          "try",
          "while",
          "return",
        ],
        prev: "*",
      },
      {
        blankLine: "always",
        next: "*",
        prev: [
          "break",
          "case",
          "cjs-export",
          "class",
          "const",
          "continue",
          "do",
          "export",
          "if",
          "let",
          "return",
          "switch",
          "try",
          "while",
        ],
      },
      {
        blankLine: "never",
        next: ["const", "let"],
        prev: ["const", "let"],
      },
      {
        blankLine: "always",
        prev: "expression",
        next: "*",
      },
      {
        blankLine: "any",
        prev: "expression",
        next: "expression",
      },
    ],
    "@stylistic/quotes": [
      "error",
      "double",
      { allowTemplateLiterals: "always", avoidEscape: true },
    ],
    "@stylistic/semi": ["error", "never"],
    "@stylistic/space-before-blocks": "error",
    "@stylistic/wrap-iife": ["error", "inside"],
    "array-callback-return": [
      "error",
      { allowImplicit: false, allowVoid: true, checkForEach: true },
    ],
    "arrow-body-style": ["error", "as-needed"],
    "capitalized-comments": ["error", "always", { ignoreConsecutiveComments: true }],
    curly: ["error", "all"],
    "default-param-last": "error",
    eqeqeq: ["error", "always"],
    "func-names": "error",
    "func-style": ["error", "declaration", { allowArrowFunctions: true }],
    "guard-for-in": "error",
    "init-declarations": ["error", "always"],
    "max-nested-callbacks": ["error", 3],
    "max-params": ["error", 3],
    "new-cap": "error",
    "no-alert": "error",
    "no-await-in-loop": "error",
    "no-case-declarations": "error",
    "no-console": "error",
    "no-constructor-return": "error",
    "no-duplicate-imports": ["error", { includeExports: true, allowSeparateTypeImports: true }],
    "no-else-return": "error",
    "no-empty": "error",
    "no-empty-function": "error",
    "no-eq-null": "error",
    "no-extend-native": "error",
    "no-extra-label": "error",
    "no-fallthrough": "error",
    "no-implicit-coercion": "error",
    "no-inline-comments": "error",
    "no-labels": "error",
    "no-lone-blocks": "error",
    "no-lonely-if": "error",
    "no-loop-func": "error",
    "no-multi-assign": "error",
    "no-multi-str": "error",
    "no-nested-ternary": "error",
    "no-new": "error",
    "no-new-func": "error",
    "no-new-wrappers": "error",
    "no-object-constructor": "error",
    "no-param-reassign": "error",
    "no-plusplus": "error",
    "no-promise-executor-return": ["error", { allowVoid: true }],
    "no-proto": "error",
    "no-prototype-builtins": "error",
    "no-redeclare": "error",
    "no-regex-spaces": "error",
    "no-return-assign": ["error", "always"],
    "no-script-url": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-shadow": "error",
    "no-template-curly-in-string": "error",
    "no-throw-literal": "error",
    "no-unexpected-multiline": "error",
    "no-unmodified-loop-condition": "error",
    "no-unneeded-ternary": ["error", { defaultAssignment: false }],
    "no-unused-expressions": ["error", { enforceForJSX: true }],
    "no-useless-call": "error",
    "no-useless-computed-key": ["error", { enforceForClassMembers: true }],
    "no-useless-concat": "error",
    "no-useless-constructor": "error",
    "no-useless-return": "error",
    "no-var": "error",
    "no-warning-comments": ["error", { terms: ["todo"] }],
    "object-shorthand": ["error", "always"],
    "operator-assignment": ["error", "always"],
    "prefer-const": ["error", { destructuring: "any", ignoreReadBeforeAssign: false }],
    "prefer-destructuring": "error",
    "prefer-exponentiation-operator": "error",
    "prefer-numeric-literals": "error",
    "prefer-object-has-own": "error",
    "prefer-object-spread": "error",
    "prefer-promise-reject-errors": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
    radix: "error",
    "require-await": "error",
    "symbol-description": "error",
    "typescript/adjacent-overload-signatures": "error",
    "typescript/array-type": ["error", { default: "array-simple", readonly: "array-simple" }],
    "typescript/ban-ts-comment": ["error", { minimumDescriptionLength: 10 }],
    "typescript/consistent-generic-constructors": "error",
    "typescript/consistent-indexed-object-style": "error",
    "typescript/consistent-type-assertions": "error",
    "typescript/consistent-type-definitions": "error",
    "typescript/consistent-type-imports": ["error", { disallowTypeAnnotations: false }],
    "typescript/dot-notation": "error",
    "typescript/no-confusing-non-null-assertion": "error",
    "typescript/no-confusing-void-expression": "error",
    "typescript/no-deprecated": "error",
    "typescript/no-dynamic-delete": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-inferrable-types": "error",
    "typescript/no-invalid-void-type": "error",
    "typescript/no-misused-promises": ["error", { checksVoidReturn: { attributes: false } }],
    "typescript/no-mixed-enums": "error",
    "typescript/no-namespace": "error",
    "typescript/no-non-null-asserted-nullish-coalescing": "error",
    "typescript/no-non-null-assertion": "error",
    "typescript/no-require-imports": "error",
    "typescript/no-unnecessary-boolean-literal-compare": "error",
    "typescript/no-unnecessary-condition": "error",
    "typescript/no-unnecessary-template-expression": "error",
    "typescript/no-unnecessary-type-arguments": "error",
    "typescript/no-unnecessary-type-assertion": "error",
    "typescript/no-unnecessary-type-constraint": "error",
    "typescript/no-unnecessary-type-conversion": "error",
    "typescript/no-unnecessary-type-parameters": "error",
    "typescript/no-unsafe-argument": "error",
    "typescript/no-unsafe-assignment": "error",
    "typescript/no-unsafe-call": "error",
    "typescript/no-unsafe-enum-comparison": "error",
    "typescript/no-unsafe-function-type": "error",
    "typescript/no-unsafe-member-access": "error",
    "typescript/no-unsafe-return": "error",
    "typescript/non-nullable-type-assertion-style": "error",
    "typescript/only-throw-error": "error",
    "typescript/prefer-find": "error",
    "typescript/prefer-for-of": "error",
    "typescript/prefer-function-type": "error",
    "typescript/prefer-includes": "error",
    "typescript/prefer-literal-enum-member": "error",
    "typescript/prefer-nullish-coalescing": "error",
    "typescript/prefer-optional-chain": "error",
    "typescript/prefer-reduce-type-parameter": "error",
    "typescript/prefer-regexp-exec": "error",
    "typescript/prefer-string-starts-ends-with": "error",
    "typescript/require-await": "error",
    "typescript/restrict-plus-operands": [
      "error",
      {
        allowAny: false,
        allowBoolean: false,
        allowNullish: false,
        allowNumberAndString: false,
        allowRegExp: false,
      },
    ],
    "typescript/restrict-template-expressions": [
      "error",
      { allowBoolean: true, allowNumber: true },
    ],
    "typescript/return-await": ["error", "error-handling-correctness-only"],
    "typescript/unified-signatures": "error",
    "typescript/use-unknown-in-catch-callback-variable": "error",
    yoda: "error",
  },
})
