name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

jobs:
  knip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        
      - name: Install dependencies
        run: bun install

      - name: Knip
        run: bun knip

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        
      - name: Install dependencies
        run: bun install

      - name: Check
        run: bun check

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        
      - name: Install dependencies
        run: bun install

      - name: Typecheck
        run: bun typecheck
